<?php

$urls = <<<SITES
krishashok.me
wendymscott.com
jewishexperienceonline.com
flabbybrain.com
hessmarketinglegal.wordpress.com
marketinmobiliario.com
nandoland.wordpress.com
latebloominglesbian.com
urubatanneto.wordpress.com
saanyagulati.com
skovkjaer.com
swansonbooks.com
iowaan.org
ilikebeingsickanddisabled.com
somewherelsewhere.com
markstabile.net
megoracle.com
sophiastreet.com
raianisibien.wordpress.com
freshfromnancysgarden.com
haidadesigns.com
wordtoyourmummy.wordpress.com
piperblogs.org
acuitypr.wordpress.com
runningonsober.com
ripcordcomm.org
aplaceforeverywoman.com
saramorgan.net
cultofconfucius.wordpress.com
industriallindah.com
robbundschu.wordpress.com
shortcutsamerica.com
thehealingdentist.wordpress.com
schulemitrespekt.wordpress.de
myearlyyears.net
felicitycurtain.com
courbrittfamily.com
brainypursuitsinsandiego.com
enandenvirkelighed.com
annesquared.com
jenvera.com
bendehaldevang.com
vidadeeditora.wordpress.com
conniemartin319.com
spacegoonsblog.com
c4sr.wordpress.com
circusgardener.com
tonoticeandtolearn.com
todayincincinnatirealestate.com
shanaliebman.wordpress.com
enticingepiphanies.wordpress.com
katyfentress.com
natural-wellness-methods.com
bloggingzen.wordpress.com
www.beautydebeauvoir.com
foodsourcecorp.com
ditsomokos.com
johnharveyblog.wordpress.com
theanticoach.wordpress.com
livingwithalphas.wordpress.com
best-acne-remedies-otc.com
melancholyhyperbole.com
gainesvilleobserved.com
iscademo.wordpress.com
witnessroomeurope.wordpress.com
jasonneilsoto.com
christinerichrealestate.wordpress.com
writingtheshadow.wordpress.com
portcitynotebook.wordpress.com
canoaristoy.wordpress.com
obedienceofchrist.wordpress.com
conqueryourcomfortzone.wordpress.com
yourvent.com
corinhughs.wordpress.com
astrologybymathilde.wordpress.com
targusblog.com
projectramon.wordpress.com
thebabygapblog.com
adwmteulings.wordpress.com
barnabasnet.com
iccssa.net
alisonflowers.com
princegarrett.com
fashionsnippets.wordpress.com
auburnmla.wordpress.com
studentartaustralia.com
chezvandy.wordpress.com
apoiandometas.com
rushinlondon.com
theswiftkick.com
stuffitalkabout.com
theseattleslew.wordpress.com
julessaysso.com
stateplay.wordpress.com
paintitrightrva.wordpress.com
ramblingvicky.wordpress.com
gradyhswritingcenter.wordpress.com
unforgettingdotco.wordpress.com
thementalhealthpost.com
beingbombdiggity.com
ccaheadmaster.wordpress.com
jlovellsjawp.wordpress.com
charleshadsalldiary.wordpress.com
bentleygrad.wordpress.com
drawntovalencia.wordpress.com
whyiamnotapoet.wordpress.com
colinherd.wordpress.com
thegoodkindofshamz.wordpress.com
casource.co.za
www.themacadames.com/
thedadhatter.com
snakes-sunrises-and-shakespeare.com
tolivetocook.com
styleandair.com
styledsimpleandnique.wordpress.com
lemongroveroad.com.au
unfulmineincucina.com
noveamaismais.wordpress.com
margosmiddlefinger.com
koreanwhispers.wordpress.com
pillbeat.wordpress.com
storiesfromthecityblog.wordpress.com
joybeautyandsweet.com
nipponbusiness.wordpress.com
sandraishuman.wordpress.com
fashioningrocks.com
mcwilson1956.wordpress.com
stilettoetbikini.com
ljasher.wordpress.com
lookatthoseclothes.wordpress.com
lauramarello.com
lhpclaw.com
tipps4moms.wordpress.com
newsexplained.wordpress.com
ramonloyola.org
steppingintoglory.com
classictimbridges.com
nicole500.wordpress.com
thatsitmyfriend.wordpress.com
lunica-music.com
thelisteningweb.com
eggplantchronicles.com
forthoodtestimonies.com
fundraising-strategist.com
brontecleary.wordpress.com
drmamaesq.com
mh17malaysia.com
bbargoni.com
geloofenredeonline.wordpress.com
intern-match.org
savoringsaturdays.com
staciebphotography.com
bbhcommoditymarketsupdate.wordpress.com
yourmeetingcoach.wordpress.com
austinjustice.pacefirm.com
eng215ha.com
nonperfectwriting.com
dokumhane.net
megoracle2.wordpress.com
SITES;

$sites = explode( "\n", $urls );

foreach( $sites as $site ) {

        $width = 400;
        $height = 300;
        $image_url = 'https://s0.wordpress.com/mshots/v1/' . urlencode( $site ) . '?w=' . $width . '&h=' . $height;

?>
<a href="http://<?php echo $site; ?>" target="_blank">
            <img src="<?php echo $image_url; ?>" width="<?php echo $width; ?>" height="<?php echo $height; ?>" />
</a>
<?php
}
