<?php

$urls = <<<SITES
vrijmoedig.net
mtlowdown.com
cenlamar.com
mundorama.net
tabbybiddle.wordpress.com
celestialtimepiece.com
heyayeh.com
alitaparavolar.com
shannonelaine.com
lorraineroe.wordpress.com
liupoyuan.wordpress.com
josemcane.com.ar
michaelhann.wordpress.com
worldmedya.wordpress.com
originalodyssey.com
bdclifeinstyle.com
spielbrot.wordpress.com
dutchgator.com
breslanta.com
yoloprueboytelocuento.wordpress.com
carysnyder.com
dailyssimo.com
crossfitravenna.com
stefaniefriedhoff.com
pouletrotique.com
blog.luxuryrestaurantguide.com
youarenotsosmart.com
bestyearyet.wordpress.com
nationalfinancecorporation.net
penseravantdouvrirlabouche.com
nicolerigets.com
andreahausmannphotography.wordpress.com
slouchingtowardsthatcham.com
janeching.com
jasesdiary.com
therealestatevine.wordpress.com
vanessaruns.com
voidformation.wordpress.com
johandecelle.wordpress.com
stylewhisperer.wordpress.com
alchemik-poznan.com
lizziephotography.wordpress.com
villmarkshistorier.no
borgesson.wordpress.com
stevegoodyear.wordpress.com
dragonistasblog.com
innovatingscotland.com
lalineadefuego.info
empressevelyn.com
financieleplanningblog.nl
marcasensalud.wordpress.com
theimaginariumofmakeup.com
dirtyblondeink.com
leticiaromerochumacero.com
samuelkee.com
marthinusstrydom.wordpress.com
withconseil.wordpress.com
locashmagazine.com
aakomon.wordpress.com
dannygregorysblog.com
adequatelyoutraged.com
motoglenn.com
dogfriendlytraveler.com
cesarcallejas.wordpress.com
pollyadams.com
changeforbusiness.wordpress.com
erinemaloneblog.com
vicariousass.com
taloudentulkki.com
violetkim.com
suefierston.wordpress.com
merrywhethers.wordpress.com
peterabrad.wordpress.com
janitoivola.net
behind-the-seens.com
alicegreschkow.com
hwnsurf.info
felixgrayson.wordpress.com
fashionstylistmb.wordpress.com
chefindisguise.com
virginiamunden.me
womenoclock.com
etsushin.com
changingthenarrative.net
domesticdivalife.wordpress.com
nonformality.wordpress.com
theboardgaminglife.com
parvina.wordpress.com
bonbonlife.com
andrewjbowe.com
mabvutojobani.com
qmpblog.com
discerningkate.com
awanderingappetite.com
smartmoneycents.com
mikkasintestblogg.wordpress.com
peacockseye.nl
nailasays.wordpress.com
blog.japancentre.com
montagpress.com
newmeast.wordpress.com
improvingpolice.wordpress.com
institutemag.com
livesaveshine.com
jeffersonandjane.wordpress.com
acronymtv.wordpress.com
diaryofadashingfashionista.com
blog.anywaydoors.be
daniethegirl.com
bumfood.com
justaddpictures.com
hansel-and-gretel.org
africanyouthjournals.com
markdegrasse.com
davidkelly.info
juxtamagazine.org
sicarnews.wordpress.com
blog.paulandmiranda.com
alinaceusan.net
wildandfreeblog.com
bohomoth.com
lajicarita.wordpress.com
fievrerouge.com
shaina90.wordpress.com
kunsthausberlinmarbella.com
iradiospin.com
timeldridge.wordpress.com
abdulnasseralshaali.com
roncowiephotoblog.com
liannecollignon.com
cassiasiqueira.com
themmatrainingbible.com
utcatalyst.com
electric-haze.net
beermasters.org
thescoopdxb.com
streettrotter.com
arturosepulveda.com
moderndaymindful.com
selectionsmj.com
warneyswhip.com
bhslionsroar.com
localsmag.com
stadiafile.com
myhollowhead.com
www.thepowderpuffpost.com
peggynairn.com
onlyjayraw.com
kolaleph.org
laurmm.wordpress.com
myfavesjournal.com
thebangaloresnob.com
imalexmiranda.com
hautearabia.me
eichl.com
hamelinjournal.com
skullandwildflower.wordpress.com
rianaetienneblog.com
janemesser.com
shaquillaalexander.wordpress.com
mamiglammy.com
afternyne.com
books-bubbles.com
sbhistoricalblog.com
digisophy.org
verysimplestuff.com
anuestroalcance.com
getdressedmommy.com
uelthegallion.wordpress.com
catherineongenae.com
veragarrett.com
myfrow.wordpress.com
diodocs.wordpress.com
ptyology.com
wholistichealthyyc.com
potoksworldphotos.wordpress.com
ilrestodelcaffe.com
talkingsofa.wordpress.com
eurekafc.com
chicagoliterati.com
donaldrdevlin.wordpress.com
jackiejadeproductions.wordpress.com
lockedandloadedtrailers.com
cristinafacundoblog.com
asuntospendientesantesdemorir.com
antakranablog.com
thewonderofarvi.com
lucypalmreports.com
pizzadive.wordpress.com
outofessex.wordpress.com
davidtrads.me
daswerk.me
themangrabber.wordpress.com
globalsouls.net
magontheblog.com
ellekayj.wordpress.com
elizabethfadoju.com
ladyberd.com
publicis-hk-leadthechange.com
iloveprimrosehill.com
vaughanmasawiey.com
onyxmaree.com
uartsmuseumcommunication.wordpress.com
leagueofextraordinarycosplayers.com
socialworkunplugged.com
crosbyp12003.wordpress.com
pabjprism.com
mydramaticweightloss.com
regionsandcities.eu
forever25blog.com
gabbysite.wordpress.com
www.maresdebarcelona.es
storgy.com
revistalogisticatender.com
leemccance.wordpress.com
madeinsydney.net
strikemagazine.co.uk
lassunsmalreden.wordpress.com
cosmosiris.me
elephantnewsgop.com
ironimus-online.org
retropolitain.me
michellejesterblog.wordpress.com
deesigninspiration.wordpress.com
heirloomcommons.wordpress.com
claudiovelardi.com
lifeofthekabmater.com
blog.marcojoefazio.com
johngreimphotography.wordpress.com
joelmwakasege.com
avgregerson.com
thebarraca.com
dreamcometruemomo.wordpress.com
collectivedit.com
coolandtrendymen.com
shelbysells.com
mhkinstl.com
sweetandsourfashionblog.com
goodmormonlife.net
canberramusicblog.com
blushlondon.co.uk
dasgutezeug.com
findyourbackbone.com
theatredelamour.com
the-educational.com
reportingdc.wordpress.com
thedistances.wordpress.com
fairlyhappy.wordpress.com
jovenesehipermedios.com
waydowninthehole.com
miacollis.wordpress.com
caminoligero.com
fashionbynorway.com
thatfabulousblackgirl.com
nexteye.org
wylieunleashed.net
thetrilogyblog.com
le-weekendblog.com
theccdshook.wordpress.com
amyelizabethburns.com
iamnaome.com
thepeoplescriticblog.com
pro-educativa.com
905whitestreet.com
portodovinho.com
jazztamez.com
donnellymclean.wordpress.com
melaniegonzalez.org
consciouslivingweeklyblog.wordpress.com
inspirativa.org
alistrealestateagents.com
southerndoemagazine.com
inspireher.co
globalgarcon.com
anthrochroma.wordpress.com
dawallstreet.com
theburlychef.com
theswedishafrican.wordpress.com
concepticolas.com
osteopractor.wordpress.com
fashionlovealex.com
thailandtoursblog.com
fareyaazfar.com
projet-honorine.com
jagorstrand.wordpress.com
oldrookie.com
advisemystyle.wordpress.com
dukeshin.com
makeupmymood.com
theworktrotter.com
aspernauts.wordpress.com
blackboardbodhisattvas.org
gentswithstyle.com
schizoaffectiveretina.com
candidlondon.com
3spro.wordpress.com
juveniltimoteo.com
alyendicottblog.wordpress.com
thechiccago.com
youresomummy.com
soparatias.wordpress.com
midnightneisense.com
mooffduty.com/
girltritalk.com
skindemics.com
losttribemagazine.com
obviweretheladies.com
popcultlife.com
heretatdesoler.wordpress.com
burnsnews.wordpress.com
simplydandydani.com
utopiacourant.nl
carmenoliverfotografiablog.com
pervalle.com
solvangpark.com
tiempobullet.com
psquaredart.co
simplerealty.wordpress.com
adamnusrallah.com
specteelive.wordpress.com
thepapersrecord.wordpress.com
hometownheroine.com
frommaybetoalmost.com
getlivted.com
voicedmotion.wordpress.com
plusdeoff.com
courtgirl.net
bukehiziroglu.com
blaqueerflow.com
thecreativescrapbook.wordpress.com
seesuffolk.com
vers-usmag.com
bostonpoliticalreview.org
obramagna.wordpress.com
dead-men-talking.de
alexandranelson.co
truelifeavenue.com
dashmeremag.com
blog.jaypore.com
the20sdiary.com
dialmainteriorsblog.com
krijtverfonlineblog.com
crunchydungeon.com
coffeeandcoutureblog.com
blog.onemorechanceboutique.com
effectofjoy.com
jameslo.org
thebottleaffair.wordpress.com
gianfrancoreyes.com
outeraislefoods.com
outofoffice.today
motorsentinel.wordpress.com
reyesjuanmanuel.wordpress.com
cesaroramirez.com
persimmonmarketing.com
joyartbyheart.com
pinkflamingodiaries.com
cerine-dipity.com
thefashiongazette.com
thecurrencyblog.com
animafrika.com
shutinghsu.wordpress.com
raisingabbeyfromthedead.com
viewfromafrenchhillside.com
theglitteredage.com
wildbybar.com
theeditorialmag.com
dorotheabeauty.com
cosmopolitely.com
petertlynas.com
blog.palestine-studies.org
ericduane.com
mandiri-rent-a-car.com
busystylebeautyblog.com
ricardovinyes.wordpress.com
modeaffe.com
ceciliaroses.com
forzasilvioclub.wordpress.com
sarahchiarello.wordpress.com
joyart.nl
mossislandsounds.com
boldbalancedbeauties.com
briandear.co
elogiodeltexto.com
mikemcfoto.com
fitterforlife.wordpress.com
youthsgonewonky.com
genesisdebateprogrammes.com
theupsidenews.com
justrellis.com
totallylegitnews.net
missdignity.wordpress.com
amalgamofjoy.com
olaterrible.com
dryadlondon.wordpress.com
teamrockblog.wordpress.com
chicenzo.com
thecocktail-lounge.com
ciudadpuente.com
juradoarchitects.com
skithemitten.net
thirtyseventhgu.com
jesusmaryandallthat.wordpress.com
stephaniegrubenmann.ch
pianezzaphotography.com
newsthailandtours.com
damastelo.com
blackinvogue.com
callingwest.com
thebackstoryscreenwritingstaffing.wordpress.com
thelilium.com
industryofcooldotnet.wordpress.com
blondebonshell.com
claudiabechstein.wordpress.com
ivanjoshualoh.com
warnerave.com
tambourinejournal.com
coppercole.com
plataformablog.com
mariahelenavolpatoplussize.wordpress.com
pejlinger.dk
whattheblueeyesspy.com
lssucompass.me
juliaomalley.media
anywayitsus.com
voirsavoir.com
humdrumblog.com
distinctmagazin.wordpress.com
badududu.com
watchgirlwork.com
thelamourcollection.com
myrhoad.com
newsliteracymatters.com
petitebonita.com
politicus.gr
karakoss.realtor
manufacturingdisruption.com
bracodemag.com
humanrethink.net
strangegypsy.com
szectattoohk.wordpress.com
johngevans54.com
clemencemusa.com
dumbmoney.net
besweettome.me
peacecorpssoutheast.com
routail.com
peacepowerlight.life
intoxicatingsilhouette.com
blog.fineartamerica.com
applesutra.com
averysmallanimal.com
thehungrymaneater.com
swansonshub.wordpress.com
indieloveblog.wordpress.com
jessicahutwelker.com
leoniemakesitup.com
luxgazete.wordpress.com
alphabhoys.wordpress.com
miss-marissalee.com
misstattinger.wordpress.com
lakelander.com
sidehitsandeurocarves.com
thedrezzstudio.com
bigdogcine.com
conversationsonliberia.com
theshedofshred.com
carriewisehart.com
modagirona.com
pixelgradesandbox.wordpress.com
hivedemo.wordpress.com
eebs.me
pequenacozinhaemsaoluis.com
londonlifeandstyle.com
ujreview.com
lovelittleadventures.wordpress.com
meilikefootball.com
santaspecadorasblog.com
lostwknd.com
worldofwim.net
invencionblog.wordpress.com
lifeforlaura.com
thennword.com
asavvygent.com
cesthoa.com
crowleym.com
juicecult.org
chateaubosgouet.wordpress.com
ilavanti.wordpress.com
disarmedandcrosschecked.wordpress.com
brandtfleming.wordpress.com
theitalianartblog.com
madryk.wordpress.com
paneuropean.care
timelesslegacy.wordpress.com
comprediretopecas.wordpress.com
thebrandyalexandermag.com
rubygolani.com
scoffgirl.com
runograf.com
theprovoan.com
desconocidaentropia.com
godsspotlight.com
bysaraalice.com
heliaphotography.wordpress.com
gesichterundgeschichten.wordpress.com
curlygreeneyedmonkey.wordpress.com
moderneastjournal.com
damianstanden.wordpress.com
janeunchained.com
ifihad10daystolive.com
lechromatographe.wordpress.com
styleoversaving.wordpress.com
noshrinkingviolets.com
rockandrolljunkie.com
philtrat.org
manufaktur75.wordpress.com
blog.wearhaus.com
thenorwegiannewsdrive.wordpress.com
mommy-magazine.nl
abkreativ.com
entredois.com
medullaprimer.com
beardsmansjournal.com
fivesecretsdottv.wordpress.com
coiffedandcultured.com
josephsullivan.net
doloresmarieke.wordpress.com
pssgt.com
oincendiario.com
clubedafertilidade.com
therevengeissue.com
indylaska.com
ezeochapost.com
batleapventures.wordpress.com
shannonkeeley.wordpress.com
thetezzyfiles.com
meandmiblog.com
kommerzblog.wordpress.com
learntotutor.wordpress.com
immunocologieskincare.wordpress.com
westslopeevents.com
talulahruffles.wordpress.com
mlmbeauty.biz
proviviendasturisticas.com
wmcphotoblog.com
pinkheartattack.com
mishkahblog.com
everydayglamor.com
themodernhustler.wordpress.com
yearofthefowlmood.com
ginghamisthenewblack.wordpress.com
lovefromleyla.com
nospetitscarnets.com
noplacetolay.com
dinasaurus82.wordpress.com
kidsyogaco.com
marshallday51.wordpress.com
barnert2014.wordpress.com
moodhotels.wordpress.com
bellehighclass.com
theoxfordproject.co.uk
the-batard-blog.com
candicenicolespeaks.com
chroniclesofcuriousyoung.com
pointemade.com
adamsadiq.com
ryanoilusa.com
2dshall.com
thecollectiveplaylist.wordpress.com
earthcodex.com
rhenaniaturicensis.com
blog.oriba.com.br
frostjakobsen.com
designschaufenster.wordpress.com
soferina.com
matheusrego.wordpress.com
rome476.com
moodlifter.com
lifeartsanat.com
backachesandcoffeebreaks.wordpress.com
gunhoppy.com
vonbk.com
lavidabonitablog.com
roundaworld.com
martinpollecoff.com
geestigmagazine.nl
coralinekrakdotnl.wordpress.com
sportandsocialclubblog.wordpress.com
magicmannila.com
thefaaside.com
enkelhetenilivet.no
fourthwallmagazine.com
thespatterbox.com
atlasaeris.com
bcdtech.me
elzatravel.com
aluxurywecanafford.com
flatteringlyfit.wordpress.com
pigeonlettersdotcom.wordpress.com
millsapspandw.wordpress.com
bendyr.com
inesdelaguerra.wordpress.com
the-australasian.com
jasonjgale.wordpress.com
awolstreetjournal.com
revistasoliloquio.com
afronomist.com
freesociety.co
blog.buckle.com
whiskeyword.com
lmary.me
ravepan.com
blog.theleopardlounge.nl
thegallivantist.wordpress.com
therabbitnewspaper.com
jdheinerblog.com
heiresssociety.wordpress.com
segundallamada.com
eightsixmag.com
workinggirlproblems.com
matteroutofplace.net
aldermanlushington.com
meritsmag.wordpress.com
bangerbulletin.com
miestilomk.com.mx
3hsofv.com
velvetblond.com
joseanrego.com
lewisyates.wordpress.com
thedergi.com
donnieboroff.com
technology2software.wordpress.com
acceptablewords.com
5dal.com
suchitravijayan.com
frontstreetjournal.racc.edu
theseppo.wordpress.com
diverscity-magazine.com
theprestigeuniversalgroups.wordpress.com
be-think-do.com
depressiespotlight.com
fashionspaceship.com
katrinarazon.com
theacscoop.wordpress.com
bullshtmgzn.com
foodieexclusive.wordpress.com
theltimes.com
concordculture.com
boonevalleydental.com
contentspower.wordpress.com
deshawnlovesmakeup.wordpress.com
divasmagazine.wordpress.com
artkrave.wordpress.com
washingtonweeklynews.com
gingerworks.co
travelingpriority.com
revistacrestina.ro
yanapokrepa.com
blog.craft2eu.net
redphoenixacademy.wordpress.com
dailynerddotcomdotbr.wordpress.com
luxman.com.au
aventartemplates.wordpress.com
thefremag.com
lesmessesbasses.com
heretodaynews.org
british-fashion.com
carnenegra.com
theindifferencecurves.com
elianenicole.com
mlmccollum.wordpress.com
bradyhardin.com
babyloveprofessionaldoulas.wordpress.com
sallyanscombephotographyblog.com
asyouwish-services.com
iop-blog.org
theignorantowl.wordpress.com
pixelgradeplay.wordpress.com
shewhotravelsau.wordpress.com
personalhair.co.uk
almostinterestingdotme.wordpress.com
lawaware.org
shouldacouldawouldabooks.com
pieldeangelspa.wordpress.com
randomissue.com
faiththatreasons.com
sweatcultured.com
evieharland.wordpress.com
ge2015.prospect.org.uk
lestartinesmariolles.com
hiddeneyemagazine.wordpress.com
hwspectrum.com
metropolitanfit.com
thejustworld.wordpress.com
renoveringpaadagsordenen.com
blog.noola.be
andrew0619.wordpress.com
fr-noos.com
thompsonexplorer.wordpress.com
shamkini.com
theblackmanproject.wordpress.com
changeabilitybook.wordpress.com
ipmmodels.wordpress.com
yogamagistanbul.com
creativechange02.wordpress.com
miliartcentre.com
olgapapina.com
selphgroup.com
stephaniecoolidgeblog.wordpress.com
relok8.me
fitfynefabulous.com
sinnkonfetti.com
bloodfeastpod.wordpress.com
murkybird.com
autotatler.com
maxwellsplaybook.com
kaelenohm.wordpress.com
hemmahosblog.com
gnistmagasinet.no
philippevandervelpen.wordpress.com
politicalronin.wordpress.com
alansmitheemovies.com
deceptionwork.com
hidalgomedia2.wordpress.com
xtremeairsoftblog.com
mcel82.wordpress.com
runfitfun.fr
martletonline.com
kikecalvoblog.com
radar30.com.br
offyourcouch.wordpress.com
deathofthepressbox.com
tomcourcey.com
thelux.company
rainpaper.com
aylaozaygen.com
stylisedmag.com
colombofasteners.info
theadora.me
robertmajenka.com
raphaelasaphira.wordpress.com
tophomexxx.com
northwestcoaststyle.com
spaceshipchina.com
grannytakessides.com
lamiacasashabby.com
citymaven.me
benitanisaro.com
a1speaks.com
shinsoftware.wordpress.com
viril.me
poeticramblingsdotorg.wordpress.com
mspflymag.com
thepinholeprojector.com
wfcgreen.com
falikl.com
street-talk-life.com
carolincavalli.wordpress.com
justhappentobeapwd.com
inhershoesrk.com
lrloves.com
reisdewereldrond.nl
lescarnetsduluxe.com
healthebrainblog.wordpress.com
historyclubmagazinedccc.wordpress.com
firststateheadlines.com
newmoralworld.com
theveganbuzz.net
empiretimes.com.au
freshouttheovenmusic.co.uk
moleandrat.com
giydimciktim.com
alive2us.com
nordostmitte.wordpress.com
fatmaerhalac.com
lemelting-pot.com
bartwelve.com
tasharchitects.wordpress.com
jneeharbowy.com
lyxnosnews.com
dabstars.wordpress.com
pervettemag.com
monsieurwilliam.co
rabiaqureshi.com
huzzars.pl
distortedculture.com
insidebrandingblog.com
rooseveltreview.com
modabgmagazine.wordpress.com
antoinebelot.org
superfoxstory.com
filmtalk.org
catherinebeblog.wordpress.com
adventuresinmybrain.wordpress.com
beyondourgates.net
thefutureperfectstories.wordpress.com
wundervolleaugenblicke.wordpress.com
turkeyhillapiary.com
narwhalsinlove.com
sagtz.wordpress.com
emzamahfooz.com
ld8628.wordpress.com
gristandchaff.wordpress.com
the-vintage.org
slothjiujitsu.com
theequagmire.com
dlloydsports.com
iapsd.com
screensandshots.com
danielazizzicomics.com
makeuptowear.com
trilltalknyc.com
ddsipost.com
lagaleriafactoriadotcom.wordpress.com
gooogleit.com
hangrydiva.com
winterinparis.com
hustleandmuse.com
bostravels.com
republicalifestyle.wordpress.com
sokmo.net
conchieshell.wordpress.com
gregonews.com
sfboots.wordpress.com
ashibata.com
madpsych.com
economictrends.com.ar
tilliejenkins.com
passthefnketchup.wordpress.com
hollywoodclassicmagazine.com
wirability.com
joefhall.com
slbstyle.com
elblogdegastromadrid.wordpress.com
stressfreebusiness.wordpress.com
blikoperic.com
danotations.com
erikdanielzimmerman.com
intrepidconnoisseur.com
pslewriters.com
tinearpress.wordpress.com
themalaysianbootroom.wordpress.com
theshutteraffair.com
capressegrave.wordpress.com
madhuofficial.wordpress.com
tuesdaytravelday.com
pedrogusmao.com.br
theinspiredchapter.com
saascribe.com
nevinholness.wordpress.com
blog.lsav.tv
fashionswisstoast.wordpress.com
glitterstarzinc.wordpress.com
visiognomik.com
angrygrrrll.com
theblackonwhiteblog.wordpress.com
publiekaanzet.wordpress.com
godsartisticchoices.wordpress.com
vistopontorevisto.wordpress.com
martinezespinosa.wordpress.com
dentonadams.com
retireddiva.com
corsoarts.com
aveloilla.net
endtag.co
hannahrasekh.com
visualhunterblog.wordpress.com
schach-blankenese.de
thespeakeasymag.com
poetwithapresspass.com
mimandleo.com
mortonsworld.com
adessovelamagazine.net
uncovered-uk.com
schwenkk.com
carltonsseries.com
creativehushblog.co
fashionreservoir.com
freebirdspeaks.wordpress.com
insultedintelligence.com
cosmeticizer.com
girlmeetslife.net
acemaisonblog.com
youmeandfrances.com
fuseflash.weareverjewelry.com
andredifelice.com
amandaceleste.com
aem-lab.de
establishedoncampus.com
bluediaryfree.wordpress.com
athletiktrainer.wordpress.com
hanayome-hanamuko.jp
lesfactoryfemmes.com
finemanners.wordpress.com
lesmesbeautyandwellness.wordpress.com
unbeige.wordpress.com
temmaisgentelendo.com
thefinancialdietblog.wordpress.com
clairelemarq.com
commentseduire.info
urbangolfblog.wordpress.com
tangiblemagazine.com
matrixroom.co
suzanneclough.wordpress.com
agenciaelandar.com
otekipop.org
thelittlejournal.com
stillme.fi
bluelinechi.com
creativesobriety.wordpress.com
blog.meisterstrasse.eu
eclecticlight.co
stephenshropshire.com
bristoleye.co.uk
aiaworldinbrief.com
sprucempls.com
sfspecialk.wordpress.com
faithatlaw.com
robynfacts.com
digisocialtech.com
ege.us
healingthebrains.com
thehorologistsclub.com
lindamusicblog.wordpress.com
piecesandprocurements.com
monticellollp.wordpress.com
piratemtl.wordpress.com
theleftoverlovers.com
montycarlos.com
sasmastandrews.com
ammenconsulting.com
jbeautyzone.com
audubonparkperspectives.org
elegantoutbursts.com
blog.satchelclothing.com
cristalvox.com.br
hplusrevue.com
messecanewyork.wordpress.com
thecucumbercut.wordpress.com
exhibitastudios.wordpress.com
fbafrica.com
ridecoattails.com
theopiatemagazine.com
lazebra.net
sldriversclub.com
salonkolumnisten.com
adaamelia.com
raffelleaffelle.com
luisespiritu.com
youbeautreviews.wordpress.com
becomingchi.com
lamiyaslimani.wordpress.com
dixiedixonphotography.wordpress.com
blog.brucestclair.com
jesustakewheel.wordpress.com
masterchatmag.com
dopepretty.com
tammagucci.wordpress.com
hannahjshih.com
caboweddingchic.com
nancevans.wordpress.com
luxelowe.wordpress.com
catalystasia.wordpress.com
globaltaxstrategy.wordpress.com
amityblaire.me
meekslepore.wordpress.com
clappertonmediaassociates.com
reunderstanding.wordpress.com
zarykasha.wordpress.com
outliersacademy.wordpress.com
laparentheseenchantee.fr
geodysseytravel.wordpress.com
richardeastportfolio.com
leblogdecarok.wordpress.com
dansklitt.dk
goudsgenieten.nl
www.queerdaily.co
jestilblog.wordpress.com
nadajones.wordpress.com
manningclark.org.au
perspektifraulrenanda.wordpress.com
spiritpost.net
laurahamiltonluxurylifestyleliving.wordpress.com
kurdbuzz.com
manningclarkhousegallery.wordpress.com
whatsupguides.wordpress.com
voguetv.ch
downtown500magazine.com
tuftsarch.wordpress.com
thegirlversion.wordpress.com
barbarosakkoyunlu.com
wearestardust.me
theharristimes.com
ouifemme.com
tannerkarin.wordpress.com
exponentnsu.wordpress.com
selectedbyrenee.com
vanelliston.com
theshawnmess.wordpress.com
egosjournal.com
ryanslounge.com
gabrielachard.com
trachtmeetslifestyle.wordpress.com
ferrumgroup.org
theurbanvillage.wordpress.com
thewearhouse-hammersalon.com
gordonstuartnews.com
hautenonchalance.com
eavesdroponmyvision.com
parker0988.wordpress.com
lcgctraining.com
lesamoursalternatives.com
nsfwquestion.wordpress.com
hewearswhat.com
lanetatdf.com
kelmarmagazine.com
sansparti.org
2wheelife.wordpress.com
the-tastemonials.com
cultholic.com
derzynischebeobachter.wordpress.com
colectivonu.com
ctaylorgo.com
kasusmagazine.com
shellahinman.com
joshhowerton.com
thisisapathetic-journal.com
onaac.wordpress.com
multimediageek.wordpress.com
salimayacoubi.com
fabbrienrico.com
lawschoolisdifferent.com
culturedyouth.com
leonxluxury.com
aglayamagazine.com
bachelorcrowd.wordpress.com
marsinsights.net
thetastypress.com
spanishimmigrantsintheus7.wordpress.com
18politics30.com
the-assemblage.com
perhapslife.com
bradkooimanrealestate.com
notjustfalafs.com
cannabisconsidered.com
thebruitissue.wordpress.com
allthebestbeauty.com
ilovemeribelfrance.com
vengodalmare.com
bhomeapp.wordpress.com
afroscientric.com
acalanda.com
journal.americanvintage-store.com
verbatimreview.wordpress.com
dutchnationalresearchgroup.wordpress.com
sylvia.ng
taylormadefirm.la
elojonuclear.wordpress.com
engineersnews.org
somewheretounpack.wordpress.com
fashionandpsyche.com
gokoandco.com.au
milancityjournal.com
jasmintaylor.net
s55.tv
billiemagazine.com
tonenotes.com
thesmartgunnews.com
heretik.com.tr
urisegarra.wordpress.com
thewealthyworksblog.com
afireblog.com
querock.mx
ffdiscount.com
my-greenstyle.com
paginafilosofica.wordpress.com
wildandfrida.wordpress.com
stylewithmi.com
ekstremtenakuzlar.wordpress.com
masqueuncuerpo.com
ninadiorio.wordpress.com
vapevendordigest.com
pointofsale.org
poliloquy.com
childmagsblog.com
apartment14.com
fishanoto.com
thedailyramen.com
svettpahjarnan.se
gmhnews.com
policyparlor.com
habit-lifestyle.com
sintitulodf.com
eitk.org
ahmen.in
thebaconbread.com
inittowhimit.com
eenvoudmagazine.nl
kaseyburkhalterdesigns.wordpress.com
pavlostog.com
peakmarketing.de
maryaluede.wordpress.com
audreyandersonstyle.wordpress.com
experthometips.com
spynewsmagazine.com
soulrichsociety.com
bestofinnovation.com
calienlacalle.wordpress.com
brixbailey.wordpress.com
fashionmakeupbye.com
hauteobjet.com
sannasund.com
ismanundpartner.com
eksnippets.wordpress.com
atelier100.com
historiandoquimica.com
wedkarskiblog.com
theafrooptimist.com
exposure-music.com
worldbeyondme.wordpress.com
politicaint.wordpress.com
legalaustralia.wordpress.com
whenwearwhat.com
sahanavavatu.com
datinginamodernworld.com
mamczasdlasiebie.pl
evasionsmagazine.com
eighteenthirtysix.com
andragogytheory.com
worldcelebrity.tv
logekjeden.wordpress.com
finoallestellle.com
marketingmissy.com
laurenslipglossary.com
championculture.com
cottesloemums.wordpress.com
architecthomexchange.wordpress.com
onthebrightside.fr
badisblog.ch
wifespride.com
onlyliveinquisitive.com
harshstream.wordpress.com
otcpress.wordpress.com
30andme.wordpress.com
zivmagazine.com
sersaberepoder.wordpress.com
theanonymousallisonsnow.wordpress.com
hegelsom.wordpress.com
blog.kptncook.com
whitneysgrace.com
rebelinanewdress.com
barbersnews.net
latitudesmag.ca
verticalcitizens.wordpress.com
session52.wordpress.com
llezza.com
deartabbi.com
fashionprotagonist.com
pressmagazine.com
vkmagazine.org
moeloe.com
lightfirevaporblog.com
mlearningprof.wordpress.com
muutosmuotoilublog.wordpress.com
step-up-club.net
consultation-metropoleamp.com
prettydirtygirls.wordpress.com
alternativemagazin.com
jujumag.com
actuallyalessandro.com
whirlmusicmag.com
infoxirimiri.wordpress.com
courrierdeparis.wordpress.com
oxford101.com
thediscerningnomads.wordpress.com
limelightimagesblog.wordpress.com
allthingsvinyl.net
whoreadswho.com
downtowngirluptownchic.com
revistaalmanaque.com
naimabarcelona.com
thefabday.com
hostekry.com
europagay.com
theparrot.co
horizon-management-magazine.com
greenpebblesmagazine.com
myhoustonastros.wordpress.com
immersing.org
deaditeden.com
1000strangers.wordpress.com
foodistafamily.com
joliparisblog.com
eclipsedword.com
revistaestepario.com
epic-apps.uk
mediabyvox.com
basicbitch.co.uk
plethoramagazine.wordpress.com
greaterevil.wordpress.com
intersticiosfalco.wordpress.com
bridgehammer.co
mandarinbeats.wordpress.com
leorasameni.com
bi-ozet.com
thewordbeat.com
lenferdesarts.com
firstyearwritingjournal.wordpress.com
pathjobs.org
dutildenim.wordpress.com
c4ad.wordpress.com
stevemaddenworld.com
funnypeculiarfunnyhaha.com
afamilyaffair.de
techtoggeryblog.com
diversalarums.com
lectito.me
checkitoutjoe.com
thesecondh.com
traceim.wordpress.com
thebigchatshow.com
asiloisola.wordpress.com
nabconvert.com
cookingrevolution.net
vanisyourman.com
lecosedimap.com
tiniwahyuni48.me
hitmemacho.com
journaldesongles.wordpress.com
jjpstuff.com
marksimoneny.wordpress.com
maximilliablog.wordpress.com
blog.fitsessions.com.au
iamtwistedcurlz.com
studioberden.wordpress.com
cojo-regardscroises.com
houseofabrantes.wordpress.com
themondayblonde.wordpress.com
anahitaway.wordpress.com
dirkstanden.com
jakeandmayablog.com
throughthechiclenses.com
theolympians.co
bulldogclassic.com
louisbaca.wordpress.com
amsfyn.com
boboberlingourmandise.wordpress.com
fivetoten.org
legentlemanloser.wordpress.com
rebellamag.com
tonitik.wordpress.com
oaspl.org
popmag.no
hijabheart.com
alternatif-mag.com
theshortgame.nyc
fashionforempowerment.wordpress.com
deluxeconfidential.com
isitjustbanter.wordpress.com
eureferendumuk.wordpress.com
blushimageboudoir.wordpress.com
claudiucoca.wordpress.com
elysiumlifebydesign.com
abelberumen.org
theleader.ca
mockeryofme.com
ninglau.com
mscloudcover.wordpress.com
shazifadam.wordpress.com
stylewatch.stelladot.com
blacktomorrow.net
pbielerblog.wordpress.com
darconi.wordpress.com
kiaekepanuku.wordpress.com
bloggendnaarmijnplekje.wordpress.com
towritefrom.wordpress.com
dasmuttersein.com
practiculinary.wordpress.com
nuwaview.wordpress.com
guillermovazquezblog.wordpress.com
biancacheah.com.au
boutiquesubrosa.com
winyanpressllc.org
kristenhoneycutt.org
thedailyration.com
thelifestylingart.wordpress.com
mindbodygoal.com
experiencerecreation.com
habitdiary.wordpress.com
thelonelycountry.com
thattimecooking.com
oigobby.wordpress.com
thekatacombsociety.com
lcdot.com
childsecurity.org
markedministry.com
thegentlemensvalet.wordpress.com
espressobookworm.wordpress.com
lovetaichi.wordpress.com
celebratethemaker.com
blog.neobus.pl
thepulsecogc.wordpress.com
blog.savvee.co.uk
visualinterculturalagency.wordpress.com
mlacima.wordpress.com
americanfeature.com
creativewarehouseinsights.wordpress.com
mrsrobinsonstyle.wordpress.com
mensvows.wordpress.com
ygenerationformula.com
thefirmseattle.com
jacobbremerblog.wordpress.com
zeitundstil.wordpress.com
cryingwithcoolclotheson.com
bccollegian.wordpress.com
annavasileva.wordpress.com
fafinska.wordpress.com
pszichogephaz.com
eduardovidartephotography.com
maneandtusk.com
nutravel.co
thefeminatrix.com
thekaleoffical.com
indiawildlifenews.com
thegalacticenquirer.wordpress.com
nobodylifestyle.wordpress.com
gcumagazine.com
penerd.com
spokedesignblog.com
cbdispatch.com
rrfff.be
lesconciergesblog.wordpress.com
ndquarterly.wordpress.com
acertainsyrup.com
harmonyprom.com
mrfashionmonk.com
otiummagazine.com
dedicationanddreamchasing.wordpress.com
canchekanek.com
groundbreakers.ch
amymorris.net
srgriffsports.com
redthreadevolution.com
dicasdobarba.net
vickydelderfield.com
makingdollarsgroup.co
ruesergegainsbourg.wordpress.com
fashionlawworks.com
elixir.la
allaboutmonochrome.com
lovemyvintage.no
thesixfigurechick.com
domphotog.com
lpe.world
benchmarklive.com
periodicomovil.wordpress.com
livingthediamondlife.wordpress.com
seeyoumag.com
hepmagazin41.wordpress.com
lacunarevista.wordpress.com
peninhand.info
hopesoup.me
madhocmagazine.wordpress.com
bluprintmagazine.com
cnewso.com
galefitness.com
houseoftmp.com
graciebusinesstest.wordpress.com
debutantdonts.com
millytritton.com
michellebloguea.com
theright2decide.wordpress.com
kimfenglerblog.wordpress.com
englishfutsalhq.wordpress.com
franklinsanity.com
javierperezvilla.com
tribedating.wordpress.com
thesatedape.com
biglewsnews.wordpress.com
peterwerth1975.wordpress.com
luxopedia.wordpress.com
whynotthoughts.com
phettle.wordpress.com
caplinventure.com
hi-sccs.com
lifeafterfing50.com
20somethingqs.wordpress.com
alphabetlifestyle.com
taizaikikou.co
millionairemindsetforwomen.wordpress.com
hairbyrachelrush.wordpress.com
crashmexico.wordpress.com
laiguille.co
floretarq2.wordpress.com
thehouseofcolour.com
playlaughpray.com
tellmeblog.com
2bsannab.wordpress.com
thefurryteacher.com
midnightmusicpublication.com
danerattire.com
redstripper.wordpress.com
jubulis.com
mowuyu2015.wordpress.com
socalsafetytrainers.wordpress.com
gainsbruh.wordpress.com
empowercuba.wordpress.com
houseoflovejoy.com
thedishy.com
thewanderingservant.com
saintgermainstation.wordpress.com
themusesocietymagazine.com
thelplab.liquiproof.co.uk
thewrightfinds.com
michisoldtimer.com
warrenstestsite.wordpress.com
trainwiseraceeasy.wordpress.com
thehotelcommunity.me
magazine-way.com
lmgchicago.com
eonfreezone.wordpress.com
thenewmiamian.net
iseasy.com.mx
dreamcclure.com
muzickoofthebackwardsdogs.wordpress.com
ashleyturing.com
superfunshit.com
roscoe2026.wordpress.com
thepepperazzi.wordpress.com
chelvielee.wordpress.com
livrossabr.wordpress.com
diaryofabeautybanker.wordpress.com
SITES;

$sites = explode( "\n", $urls );

foreach( $sites as $site ) {

        $width = 400;
        $height = 300;
        $image_url = 'https://s0.wordpress.com/mshots/v1/' . urlencode( $site ) . '?w=' . $width . '&h=' . $height;

?>
<a href="http://<?php echo $site; ?>" target="_blank">
            <img src="<?php echo $image_url; ?>" width="<?php echo $width; ?>" height="<?php echo $height; ?>" />
</a>
<?php
}
